CREATE DATABASE VILLASHOTEL
USE VILLASHOTEL


CREATE TABLE ROOMTYPES(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(50) NOT NULL,
PRICE MONEY
)

INSERT INTO ROOMTYPES VALUES('VIP',1000)
INSERT INTO ROOMTYPES VALUES('DELUXE',2000)
INSERT INTO ROOMTYPES VALUES('MIDDLE',300)
INSERT INTO ROOMTYPES VALUES('STANDART',700)
SELECT*FROM ROOMTYPES

CREATE TABLE ROOMS(
ID INT PRIMARY KEY IDENTITY,
[NAME] NVARCHAR(50) NOT NULL,
ROOMTYPESID INT REFERENCES ROOMTYPES(ID),
PERSONCOUNT INT NOT NULL
)

INSERT INTO ROOMS VALUES('100A',1,5)
INSERT INTO ROOMS VALUES('101B',2,4)
INSERT INTO ROOMS VALUES('101C',3,2)
INSERT INTO ROOMS VALUES('102C',4,2)
INSERT INTO ROOMS VALUES('101D',1,2)
SELECT*FROM ROOMS

CREATE TABLE CUSTOMERS(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(50) NOT NULL,
SURNAME NVARCHAR(50) NOT NULL,
PASSWORDID NVARCHAR(50) NOT NULL UNIQUE,
ROOMSID INT REFERENCES ROOMS(ID),
PhoneNum NVARCHAR(50) NOT NULL ,
Email NVARCHAR(100) NOT NULL
)
INSERT INTO CUSTOMERS VALUES('ALI','VALIYEV','7YDA9G9',1,'+523465461313','A@GMAIL.COM')
INSERT INTO CUSTOMERS VALUES('GEORGE','MARTIN','4Y6GTWG4',2,'+51628097362','G@GMAIL.COM')
INSERT INTO CUSTOMERS VALUES('DAN','BROWN','Y4GWTEJY5',3,'+56107927847','D@GMAIL.COM')
INSERT INTO CUSTOMERS VALUES('LEV','TOLSTOY','O96K7TIJ',4,'+809785674648','L@GMAIL.COM')
INSERT INTO CUSTOMERS VALUES('HARPER','LEE',';86L75IKR',5,'+132453658769','H@GMAIL.COM')
SELECT*FROM CUSTOMERS

CREATE TABLE PAYMENTS(
ID INT PRIMARY KEY IDENTITY,
RESERVATIONID INT REFERENCES RESERVATIONS(ID),
CUSTOMERSID INT REFERENCES CUSTOMERS(ID),
ROOMTYPESID INT REFERENCES ROOMTYPES(ID),
ALLAMOUNT MONEY 
)

INSERT INTO PAYMENTS VALUES(1,1,1,10000)
INSERT INTO PAYMENTS VALUES(2,2,2,7000)
INSERT INTO PAYMENTS VALUES(3,3,3,3000)
INSERT INTO PAYMENTS VALUES(3,3,4,2000)
INSERT INTO PAYMENTS VALUES(3,3,4,5000)
SELECT*FROM PAYMENTS

CREATE TABLE RESERVATIONS(
ID INT PRIMARY KEY IDENTITY,
CUSTOMERSID INT REFERENCES CUSTOMERS(ID),
ROOMSID INT REFERENCES ROOMS(ID),
RESERVATIONDATE DATE,
[DAYS] INT
)

INSERT INTO RESERVATIONS VALUES(1,1,'2020/05/17',7)
INSERT INTO RESERVATIONS VALUES(2,2,'2021/07/21',4)
INSERT INTO RESERVATIONS VALUES(3,3,'2022/06/11',3)
INSERT INTO RESERVATIONS VALUES(4,5,'2020/06/10',1)
INSERT INTO RESERVATIONS VALUES(5,5,'2021/09/17',3)
SELECT*FROM RESERVATIONS

CREATE VIEW GETCUSTOMERS
AS
SELECT C.NAME,C.PASSWORDID,R.[NAME] 'ROOM' FROM CUSTOMERS C
JOIN  RESERVATIONS RS
ON 
RS.CUSTOMERSID=C.ID 
JOIN ROOMS R
ON R.ID = C.ROOMSID
SELECT*FROM GETCUSTOMERS


CREATE VIEW GETRESERVATIONS
AS
SELECT r.RESERVATIONDATE, RS.[NAME]'ROOM', C.[NAME] 'NAME' , C.SURNAME 'SURNAME' , C.PASSWORDID 'PASSWORDID', C.Email 'EMAIL', C.PhoneNum 'PHONENUM' FROM RESERVATIONS R
JOIN ROOMS RS
ON RS.ID = R.ROOMSID
JOIN CUSTOMERS C
ON C.ID=R.CUSTOMERSID
SELECT*FROM GETRESERVATIONS

CREATE PROCEDURE SHOWRESERVATIONS @ID INT
AS
SELECT r.RESERVATIONDATE, RS.[NAME]'ROOM', C.[NAME] 'NAME' , C.SURNAME 'SURNAME' , C.PASSWORDID 'PASSWORDID', C.Email 'EMAIL', C.PhoneNum 'PHONENUM' FROM RESERVATIONS R
JOIN ROOMS RS
ON RS.ID = R.ROOMSID
JOIN CUSTOMERS C
ON C.ID=R.CUSTOMERSID
WHERE @ID=R.ID
EXEC SHOWRESERVATIONS 1


CREATE FUNCTION GetRESERVATIONDATE (@RESERVATION INT)
RETURNS DATE
AS
BEGIN
	DECLARE @DATE DATE
	SELECT @DATE=R.RESERVATIONDATE FROM RESERVATIONS AS R
	WHERE @RESERVATION=R.ID
	RETURN @DATE 
END

SELECT [DBO].[GetRESERVATIONDATE](1)


--TRIGGER
CREATE TRIGGER ADDCUSTOMER
ON Customers
AFTER INSERT
AS
BEGIN
	SELECT * FROM Customers
END

INSERT INTO CUSTOMERS VALUES('BRANDON','SANDERSON','563UUYRT',1,'+058649735863','B@GMAIL.COM')

CREATE TRIGGER ADDRESERVATION
ON RESERVATIONS
AFTER INSERT
AS
BEGIN
	SELECT * FROM RESERVATIONS
END

INSERT INTO RESERVATIONS VALUES(1,3,'2020/09/17',3)